In [2]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns',100)

In [3]:
hitter_2018 = pd.read_csv('data/2018_hitter.csv')
hitter_2019 = pd.read_csv('data/2019_hitter.csv')
hitter_2020 = pd.read_csv('data/2020_hitter.csv')
hitter_2021 = pd.read_csv('data/2021_hitter.csv')

hitter = pd.concat([hitter_2018, hitter_2019,
                    hitter_2020, hitter_2021])

player_2018 = pd.read_csv('data/2018_player.csv', encoding='cp949')
player_2019 = pd.read_csv('data/2019_player.csv', encoding='cp949')
player_2020 = pd.read_csv('data/2020_player.csv', encoding='cp949')
player_2021 = pd.read_csv('data/2021_player.csv', encoding='cp949')

player = pd.concat([player_2018, player_2019,
                    player_2020, player_2021])

batting_2018 = pd.read_csv('data/2018_batting.csv', encoding='cp949')
batting_2019 = pd.read_csv('data/2019_batting.csv', encoding='cp949')
batting_2020 = pd.read_csv('data/2020_batting.csv', encoding='cp949')
batting_2021 = pd.read_csv('data/2021_batting.csv', encoding='cp949')

batting = pd.concat([batting_2018, batting_2019,
                     batting_2020, batting_2021])

hitter.columns = ['연도','선수코드','경기','타석',
                  '타수','타율','안타','홈런',
                  '루타','장타율','희생플라이','볼넷',
                  '삼진','고의사구','사구','병살타']

player.columns = ['연도','선수코드','선수명','팀코드',
                  '포지션','나이','연봉']

batting.columns = ['연도','경기코드','타구코드','선수코드',
                   '팀코드','이닝','타구속도','발사각도',
                   '타석결과','상대투수 타구구속','구장']

batting = batting[['연도','선수코드','경기코드','타구코드',
                  '팀코드','이닝','타구속도','발사각도',
                  '타석결과','상대투수 타구구속','구장']]

In [4]:
pred10 = player[(player['선수코드'] == 76232) | (player['선수코드'] == 68050) |
                (player['선수코드'] == 75847)   | (player['선수코드'] == 67341) |
                (player['선수코드'] == 79192) | (player['선수코드'] == 78224) |
                (player['선수코드'] == 78513) | (player['선수코드'] == 76290) |
                (player['선수코드'] == 79215) | (player['선수코드'] == 67872)]  

name = ['양의지', '강백호',' 최정','이정후','채은성',
        '김재환','전준우','김현수','박건우','로맥']

pred10['선수명'] = name * 4

pred10['연봉'] = np.where(pred10['연봉'].str[-2:] == "달러", 
                          pred10['연봉'].str[:-2].astype('int64')*1200,
                          pred10['연봉'].str[:-2].astype('int64')*10000)

pred10 = pd.merge(pred10, batting)

def month(data):
    data = str(data)
    return int(data[4:6])

def day(data):
    data = str(data)
    return int(data[6:8])

pred10['월'] = pred10['경기코드'].apply(lambda x: month(x))
pred10['일'] = pred10['경기코드'].apply(lambda x: day(x))

pred10 = pred10.drop(['포지션','경기코드','타구코드'], axis=1)

pred10 = pred10[['선수코드','선수명','연도','월','일','팀코드','나이','연봉', '이닝',
                 '타구속도', '발사각도', '타석결과','상대투수 타구구속','구장']]

pred10 = pd.merge(pred10, hitter)

<ipython-input-4-3f04fadbd352>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pred10['선수명'] = name * 4
<ipython-input-4-3f04fadbd352>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pred10['연봉'] = np.where(pred10['연봉'].str[-2:] == "달러",

In [5]:
display(pred10.head())
print(pred10.shape)

,선수코드,선수명,연도,월,일,팀코드,나이,연봉,이닝,타구속도,발사각도,타석결과,상대투수 타구구속,구장,경기,타석,타수,타율,안타,홈런,루타,장타율,희생플라이,볼넷,삼진,고의사구,사구,병살타
0,67341,양의지,2018,3,24,WO,19,110000000,4,151.98,18.4,2루타,132.66,고척,109,520,459,0.355,163,6,219,0.477,8,42,58,3,8,5
1,67341,양의지,2018,3,24,WO,19,110000000,5,141.49,23.0,플라이,141.79,고척,109,520,459,0.355,163,6,219,0.477,8,42,58,3,8,5
2,67341,양의지,2018,3,24,WO,19,110000000,7,85.37,40.8,2루타,143.72,고척,109,520,459,0.355,163,6,219,0.477,8,42,58,3,8,5
3,67341,양의지,2018,3,25,WO,19,110000000,3,157.04,9.3,1루타,140.87,고척,109,520,459,0.355,163,6,219,0.477,8,42,58,3,8,5
4,67341,양의지,2018,3,25,WO,19,110000000,5,110.23,-11.1,땅볼아웃,135.64,고척,109,520,459,0.355,163,6,219,0.477,8,42,58,3,8,5

(12836, 28)

In [6]:
pred10.to_csv('data/pred10.csv')